### ISSUE TITLE
 Error in retrieving token: "Missing or invalid client credentials."

### ISSUE THREAD

**Issue by MokeyII** [GoldenGnu/dokuwiki-plugin-evesso#2]
When Trying to login via ESI, this is the error I receive. 

Error in retrieving token: "Missing or invalid client credentials."
It is getting to the page with my characters, however when returning to dokiwiki, i have that error.
I tried it on a live site and locally, both returning the same error
```
#0 C:\wamp64\www\wiki\lib\plugins\evesso\phpoauthlib\src\OAuth\OAuth2\Service\AbstractService.php(120): OAuth\OAuth2\Service\EveOnline->parseAccessTokenResponse('{"error":"inval...')
#1 C:\wamp64\www\wiki\lib\plugins\evesso\classes\AbstractAdapter.php(107): OAuth\OAuth2\Service\AbstractService->requestAccessToken('wxpRf0pNIkedTSb...', 'eyJzdGF0ZSI6IjQ...')
#2 C:\wamp64\www\wiki\lib\plugins\evesso\auth.php(96): OAuth\Plugin\AbstractAdapter->checkToken()
#3 C:\wamp64\www\wiki\inc\auth.php(101): auth_plugin_evesso->trustExternal('', '', false)
#4 C:\wamp64\www\wiki\inc\init.php(215): auth_setup()
#5 C:\wamp64\www\wiki\doku.php(34): require_once('C:\\wamp64\\www\\w...')
#6 {main}``` 


How would I fix this?

**Comment by MokeyII** [comment]
Trailing white space when Copy/Pasting Client ID and Secret Key...
Problem Solved...
😠
